### PR TITLE
#207: Refresh the scene graph every time fxomDocument did change

### PR DESCRIPTION
**Pull request by jperedadnr**

### CODE REVIEW

**Comment by jperedadnr** [comment]
To reproduce the issue you will need some custom controls added (i.e TilesFX)

**Comment by abhinayagarwal** [comment]
Please update the license header

**Comment by jperedadnr** [comment]
@abhinayagarwal Can you test the first version of this PR with just this changeset https://github.com/gluonhq/scenebuilder/pull/208/commits/dbc9af4a6f21de9f7aacc00295963c157c295647 ?

**Comment by abhinayagarwal** [comment]
@jperedadnr I can confirm that the fix in the above mentioned changeset does fix the issue :)

**Comment by jperedadnr** [comment]
Ok, great. Do you think I should revert this PR to that changeset instead?

**Comment by abhinayagarwal** [comment]
Sure.

**Comment by jperedadnr** [comment]
Ok, done, @abhinayagarwal please review

**Pull request merged**
