### PR TITLE
Lower required Java level to 21

### LINKED ISSUE #721: Java language level for Scene Builder Kit
Kit and App are built with same Java level as JavaFX release (currently 23).
While this is not an issue for App, which is distributed with its own JRE, if other third party projects want to use Kit, they are forced to set up the same level, and this shouldn't be the case: Kit should be built with the lower level possible (currently 21) 

### Expected Behavior

Kit should work for any Java 21+ project.

### Current Behavior
Adding Kit to a project running with Java level 21 gives:
```
[ERROR] [4,38] module not found: com.gluonhq.scenebuilder.kit
```

### PR DESCRIPTION
**Pull request by jperedadnr**
### Issue

Fixes #721

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Review by abhinayagarwal — DISMISSED** [review]

**Review by johanvos — APPROVED** [review]
Might be good to replace the commit message to "lower *required* Java level to 21"
(avoiding worries from people who think that they can't use Java 23)

**Comment by Oliver-Loeffler** [comment]
> Might be good to replace the commit message to "lower _required_ Java level to 21" (avoiding worries from people who think that they can't use Java 23)

We can make a statement about this setup in [README.md Requisites Section](https://github.com/gluonhq/scenebuilder/blob/jperedadnr-patch-1/README.md#requisites). @jperedadnr Could you please add this change? When adding this, could you please attempt to rephrase the commit message?

**Review by Oliver-Loeffler — CHANGES_REQUESTED** [review]
Could you please update [README.md Requisites Section](https://github.com/gluonhq/scenebuilder/blob/jperedadnr-patch-1/README.md#requisites) accordingly?

**Comment by jperedadnr** [comment]
I've updated the readme, that now says Java 21 or later, so that is good enough I guess.

**Review by Oliver-Loeffler — APPROVED** [review]

**Comment by jperedadnr** [comment]
The commit message will take the PR's title once squashed and merged

**Pull request merged**
