### PR TITLE
test: Added JobManagerTest

### PR DESCRIPTION
**Pull request by AlmasB**
Added a test for JobManager

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Review by abhinayagarwal — APPROVED** [review]

**Comment by AlmasB** [comment]
@abhinayagarwal shall we sneak this in before next release, no prod code change so should be safe to merge.

**Comment by abhinayagarwal** [comment]
Yes, definitely 👍

**Comment by abhinayagarwal** [comment]
@AlmasB Are you planning to merge this PR?

**Comment by AlmasB** [comment]
Please go ahead with the merge if you are available, or I can do that later
in the week. Thanks

**Pull request merged**
