### PR TITLE
UserLibrary Workspace and others

### PR DESCRIPTION
**Pull request by mimmoz81**
ADD LibraryDialog workspace management
  - users can link external jars/fxmls or folders to a workspace that is saved in a xml file inside the userlibrary folder.
  - ability to import/export a workspace
  - command line parsing the workspace: a new switch --ws can be passed to instruct SB to load that workspace (e.g. in Windows launching SceneBuilder.exe --ws="C:\Users\donaldduck\myworkspace.xml")
  - the last workspace imported in SB is persistent, meaning that it behaves like regular jars/folders added to the library as before. The workspace can be altered by using an import or by launching SB with the command line switch --ws
  - workspace is saved in xml format using XStream library (gradle "com.thoughtworks.xstream:xstream:1.4.11.1")
immagine

ADD DocumentWindowController refresh library menuitem: using this command the library is refreshed from scratch; this is especially useful when dealing with changing binaries in linked folders
immagine

ADD DocumentWindowController when closing the last non-empty window, a new empty window is opened instead: this avoids closing SB when the last window is closed so that a fresh new window appears. This is behaving more like other softwares (see gimp). If the last empty window is closed, SB terminates as usual.

ADD HierarchyTreeViewController, ContentPanelController pressing ESC on hierarchy treeview or on contentPane selects the parent of the current selected control (like other wysiwyg editors..)

FIX LibraryPanelController the library was trying to copy the same jar file on itself when updating filters after the ImportWindowController dialog

FIX LibraryFolderWatcher the watchService was never stopped and remained active forever; multiple overlapping services (each with its own thread) were started everytime a library update was needed (basically, a watchService.close() was missing in the thread runnable..)

Notes:
 - XStream has been used to read and write xml documents, applying the security mechanisms described [here](https://stackoverflow.com/questions/44698296/security-framework-of-xstream-not-initialized-xstream-is-probably-vulnerable).
  I had to add this to command line to "open" some package to reflection (even java.desktop was needed :O) 
`--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED`
 - We now have 2 ListViews in LibraryDialog. Maybe this is not desirable or does not its best about UserExperience.. please share your thoughs about that. I could refactor it to just have a single ListView with some sort of gui decoration for items belonging to the workspace and for items beloning to the "installed library".. I implemented it using a double ListView because that made me think more clearly that item on the left are installed permanently on SB while items on the right are replaced after every relaunch using --ws command line arg.
 - #234 is for sure conflicting with this PR

### CODE REVIEW

**Comment by mimmoz81** [comment]
just added some references in issues about custom controls and workspaces.. :)

**Comment by FilloFolla** [comment]
Thanks mimmoz81! You are making a great work, always useful for begginer users like me :)

**Comment by mimmoz81** [comment]
Glad to be helpful to you!

**Comment by mimmoz81** [comment]
Having used this for our use cases for some time, I found it very useful and I would really like to see it merged into official SB.
Is there anything more I can do? I see no reaction from Gluon since 2 months..

**Comment by georgemoralis** [comment]
nice fixes i added it to my fork and fixed an issue with FileNotFoundException with the following commit

https://github.com/codebbgr/scenebuilder/commit/4aa79ae0cbd9d3e12144db12664b1b8dd7957fb1

**Comment by mimmoz81** [comment]
Hello,
XStream does not seem to throw a FileNotFoundException in its API (fromXML() method): it would be documented in its API since FileNotFoundException is a checked IOException. Every Exception XStream can raise is a XStreamException.

Can you share your stacktrace?

**Comment by mimmoz81** [comment]
In the meanwhile, I noticed a missing MalformedURLException.. ;)

**Comment by georgemoralis** [comment]
com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:126)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1413)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1360)
	at com.oracle.javafx.scenebuilder.kit.library.user.ws.UserLibraryWorkspace.fromXml(UserLibraryWorkspace.java:103)
	at com.oracle.javafx.scenebuilder.kit.library.user.UserLibrary.<init>(UserLibrary.java:130)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleLaunch(SceneBuilderApp.java:393)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStartGeneric(AppPlatform.java:135)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStart(AppPlatform.java:103)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.start(SceneBuilderApp.java:357)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.FileNotFoundException: C:\Users\snow\AppData\Roaming\Scene Builder\Library\library-workspace.xml (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at java.base/java.net.URL.openStream(URL.java:1162)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:109)
	... 17 more

**Comment by mimmoz81** [comment]
Thanks for sharing.

com.thoughtworks.xstream.io.StreamException inherits from c.t.x.XStreamException that is the base class of all the possible exceptions thrown by XStream library, hence, there is not need to add FileNotFoundExeption catch clause (even because FileNotFoundException is just the inner cause of StreamException).
As I wrote before, FileNotFoundException is a checked exception and if not declared in XStream APIs, it is impossible for that exception to be thrown directly.

**Comment by mimmoz81** [comment]
Ok, maybe I can better handle that situation: having an exception logged for a non existing-file is not ideal.. a warn message should be enough..

**Comment by Oliver-Loeffler** [comment]
Don't think that #324 is conflicting. Having such a workspace configuration seems advantageous to me. When working with multiple workspaces, projects, I'd like to have different configurations for SceneBuilder. So this would be a great extension.
I would welcome this enhancement.

To make this more user friendly it would be nice, to select the workspace already during application startup.
Before the template screen is shown - or inside the template screen - the workspace selection could be placed.

**Comment by mimmoz81** [comment]
Sorry @Oliver-Loeffler, but I said that #234 is conflicting, not #324.
#324 is newer than this PR, and is offcourse a good one.
I someone tells me that this PR is going to be merged, maybe I could find some spare time to fix the conflicts..

**Comment by Oliver-Loeffler** [comment]
@mimmoz81 Thanks for the hint, sorry for confusing that. I really like the idea of this PR. May be @abhinayagarwal and @jperedadnr can review this if this is a welcome change. 

Personally, I think this would enhance usability a lot. Next days I'll dive into the code. May be I can support you somehow.

**Comment by abhinayagarwal** [comment]
This single PR is trying to do a lot of things. My suggestion would be to log an issue for each bug fix/feature and then create separate PRs for each one of them.

**Comment by mimmoz81** [comment]
Hi @abhinayagarwal, thanks for your feedback.
I will try to find some time to split into multiple issues:
1. ADD LibraryDialog workspace management
2. ADD DocumentWindowController refresh library menuitem
3. ADD DocumentWindowController when closing the last non-empty window, a new empty window is opened instead
4. ADD HierarchyTreeViewController, ContentPanelController pressing ESC on hierarchy treeview
5. FIX LibraryPanelController the library was trying to copy the same jar file on itself when updating filters after the ImportWindowController dialog
6. FIX LibraryFolderWatcher the watchService was never stopped and remained active forever

Can you confirm that including XStream as a dependency is not an issue (issue 1 in this list)?

**Comment by abhinayagarwal** [comment]
The multiple issues looks good.

Both XStream and Scene Builder are published under 3-Clause BSD License. Unless there is a performance impact, I don't see a problem.

**Comment by abhinayagarwal** [comment]
Hi @mimmoz81 ,

I am closing this PR in favour of splitting this into multiple PRs. I would suggest to at least create the issues so that we can keep track on what needs to be done :)

**Pull request closed without merging**
