### PR TITLE
Scan test resources for controller class

### PR DESCRIPTION
**Pull request by n-e-g**
Migrated from bitbucket, plus removed sysouts (sorry for that)

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Thank you for your patience. I have finally got the chance to review this PR.

The basic functionality of scanning the Controller classes from the test directory does work except a small issue. The drop down of the Controller class in Scene Builder appends `java` at the start of the package name for all Controller classes scanned from test directory. Once this is fixed, this PR should be good to be merged.

**Comment by abhinayagarwal** [comment]
Please update the license header to add the following at the start:

```
Copyright (c) 2019, Gluon and/or its affiliates.
```

**Comment by n-e-g** [comment]
@abhinayagarwal 
> Scene Builder appends `java` at the start of the package name for all Controller classes scanned from test directory

Thanks for comment. Could you, please send a screenshot of this issue including maybe directory structure, as I cannot reproduce this issue (on both test/java and main/java resources)

**Comment by abhinayagarwal** [comment]
It seems there was some mistake with the test data in my initial test of this PR. I cannot reproduce the issue anymore.

**Comment by jperedadnr** [comment]
Hi, @n-e-g, before we can merge your PR, we'll need you to sign this [CLA](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY). Thank you.

**Comment by n-e-g** [comment]
CLA complete

**Pull request merged**
