### PR TITLE
Added initial draft of contribution workflow

### LINKED ISSUE #307: Create a CONTRIBUTING doc
We need to be more clear about how people can contribute. We should be very open to issues, PR's and reviews, but the process needs to be clear.
In general, a PR should refer to an issue, and it should contain a test that fails before the patch, and succeeds after the patch. Also, we should provide guidelines for PRs, so that the review process becomes slightly simpler.

### PR DESCRIPTION
**Pull request by AlmasB**
### Issue

Fixes #307 

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by Oliver-Loeffler** [comment]
Hi @AlmasB, this is a very good starter. I am not sure yet how to name it, but we should add a section in limitations as well. There are PRs and Issues where it is asked to add/integrate 3rd party libraries to a certain extent. This can be a tricky thing and it should be clarified if this is indeed something desireable.

**Comment by AlmasB** [comment]
3rd party libraries: I don't think they should be present in `kit` or `app`. In the future, perhaps there can be a separate module, for example `plugins`, that would allow easy extension of SB with 3rd party libraries. However, in the meantime I will not be considering any such extensions, unless approved by other maintainers.

In terms of documentation, I would have thought what you describe falls under `Any new API or changes to existing API should be discussed to avoid inconsistencies.`. So PRs that do not target an issue that is approved for development would be unlikely to get merged. It's a balancing act I suppose: we do not wish to have PRs that are not aligned with the project goal, but at the same time we do not want to discourage people from contributing.

In light of this, perhaps there should be a project aim, or milestone aim, document for the near future -- a strategy of sorts that would underpin major decisions.

**Comment by Oliver-Loeffler** [comment]
Very well said @AlmasB , I really like the idea of having a plugin interface to allow use of external libraries.
Will be the goal of Scene Builder? What will be the vision of this project? Very good question indeed.
As it can be hard to decide what a goal for Scene Builder can be, we could collect desired key properties of Scene Builder.

**Comment by AlmasB** [comment]
I propose this short-term project goal. For the next months, until April 2022, this project will aim:

1. to add more tests.
2. to clean up existing code with a focus on readability, null safety and other improvements to facilitate future maintenance and reduce "entry cost" for new contributors.

During this period, I will refer new features and bug fixes to other project maintainers, as I cannot make informed decisions on these just yet.

**Review by johanvos — APPROVED** [review]
Concise and clear, good job.

**Comment by johanvos** [comment]
I agree with the limitations on third party libraries. It's easy to add a 3th party library, but it is hard to maintain that dependency.

**Pull request merged**
