### PR TITLE
fix: Add missing module to kit and update versions

### LINKED ISSUE #728: Attach DisplayService is needed in Kit
After #720, loading the mobile template Basic Screen fails:
```
Caused by: java.lang.ClassNotFoundException: com.gluonhq.attach.display.DisplayService
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
 ```

The DisplayService dependency should be build time (no runtime) and the display module should be added to Kit.

### PR DESCRIPTION
**Pull request by jperedadnr**
### Issue

Fixes #728

### Progress

- [x] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [ ] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [ ] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Please update the title to follow [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)

**Comment by jperedadnr** [comment]
Done

**Comment by Oliver-Loeffler** [comment]
Hi @jperedadnr, while testing, I found now that one cannot longer open the preferences dialog. I was starting Scene Builder using Maven on command line with `mvn javafx:run -f app`. It nicely launches and one can open the provided templates and also existing FXML files. But, the preferences dialog is not showing up. I'll investigate and will see, if it can be resolved within this PR or if it requires another PR.

**Review by Oliver-Loeffler — APPROVED** [review]
This looks good to me, besides the issue with the Preferences dialog. But there I'll create a new issue.

**Pull request merged**
