### PR TITLE
Move InfoPanelController to kit module

### PR DESCRIPTION
**Pull request by TobiasAsk**
As all other panel controllers reside in the kit module, there is no reason why the InfoPanelController shouldn't be there, as well.

### CODE REVIEW

**Comment by TobiasAsk** [comment]
This fixes issue #157.

**Comment by abhinayagarwal** [comment]
Please update the year in the license header of all the affected files.

**Comment by TobiasAsk** [comment]
> Please update the year in the license header of all the affected files.

Will do.

**Comment by jperedadnr** [comment]
Hi, @TobiasAsk , before we can merge your PR, we'll need you to sign this [CLA](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY). Thank you.

**Comment by TobiasAsk** [comment]
> Hi, @TobiasAsk , before we can merge your PR, we'll need you to sign this [CLA](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY). Thank you.

Done!

**Pull request merged**
