### PR TITLE
build: Added .editorconfig to project

### LINKED ISSUE #485: Provide .editorconfig in project to ensure consistent formatting
Scene Builder code follows a certain formatting style. E.g. spaces are preferred over tabs.
Add a notice either to README.md or to CONTRIBUTING.md, that Netbeans, Eclipse and VSCode require a plugin and IntelliJ does not. Add a link to https://editorconfig.org/.

### Expected Behavior
When Scene Builder project is opened in IDE, code formatting rules and styles are imported from .editorconfig.
Let Maven run the required checks (additionally to check style) [editorconfig-maven-plugin](https://ec4j.github.io/editorconfig-maven-plugin/). 

Setup to start with setup:
* no tabs, just spaces, 4 spaces indent, default line break to `\n` for `*.java`, `*.css` and `*.properties`
* add or complement README.md or CONTRIBUTING.md with a section on how to properly setup development environment

### Current Behavior
When Scene Builder project is opened in IDE, existing formatting conventions in IDE may break existing format in files.

### Context
Code formatting and use of spaces/tabs is a recurring issue in PRs and is time consuming and annoying for contributors and reviewers.

### PR DESCRIPTION
**Pull request by Oliver-Loeffler**
### Issue

Fixes #485

Adds a very basic `.editorconfig` to the project and the related Maven plug-in to automatically format files on demand.
README.md has been updated accordingly on how to make use of EditorConfig and where to get the plug-in's for the IDEs.

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] The PR name must follow the [pre-defined format](https://github.com/gluonhq/scenebuilder/blob/master/CONTRIBUTING.md)
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### Remark 2024-03-19:
The Maven plugin has been removed as the setup did actually not work as expected. However, the `.editorconfig` works well in IntelliJ IDEA and Eclipse (when equipped with the plugin).

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
@AlmasB should this be PR be marked as `build` or `feat` ?

**Comment by AlmasB** [comment]
@abhinayagarwal yeah looks like a `build` PR

**Comment by Oliver-Loeffler** [comment]
Well, the Maven Plugin is not really working as expected. Hence my proposal is to remove it. However, I'll contact the author and will ask for help there.

Nevertheless, we can keep the `.editorconfig` file as this is directly supported by IntelliJ IDEA and (via plugin) by Eclipse. Having this file and a suitable IDE will nevertheless make life easier as the IDE uses the format settings as defined in there.

For now, I've removed the Maven plugin. If we want to reformat, we could still apply checkstyle. Checkstyle works.

**Comment by abhinayagarwal** [comment]
Yes, checkstyle is a good option. Let's take it up as a separate issue.

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
