### PR TITLE
Fix early-access GH workflow

### PR DESCRIPTION
**Pull request by aalmiray**
Remove app-version input from bundles-kit.yml invocation

### Issue

Early-access workflow is broken due to an unrecognized input

### Progress

- [x] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Should [this line](https://github.com/gluonhq/scenebuilder/blob/master/.github/workflows/early-access.yml#L20) be:

```
APP_VERSION: ${{ steps.vars.outputs.APP_VERSION }}
```

We [seem to be using](https://github.com/gluonhq/scenebuilder/blob/master/.github/workflows/early-access.yml#L71) the following:

```
app-version: ${{ needs.precheck.outputs.APP_VERSION 
```

**Comment by abhinayagarwal** [comment]
Also, [setup-java still doesn't have 17.0.2](https://github.com/abhinayagarwal/scenebuilder/runs/4955526786?check_suite_focus=true#step:3:18). We should downgrade to 17.0.1.

**Comment by aalmiray** [comment]
Indeed. Let me restart this fix.

**Comment by abhinayagarwal** [comment]
I have logged https://github.com/gluonhq/scenebuilder/issues/499 to monitor this issue.

**Pull request closed without merging**
